version: '3.8'

services:
  # Frontend Production Service
  # frontend:
  #   build:
  #     context: ./UserAccessManager
  #     dockerfile: Dockerfile.prod
  #   container_name: fertiwell-frontend-prod
  #   ports:
  #     - "80:80"
  #   environment:
  #     - NODE_ENV=production
  #     - VITE_API_URL=http://localhost:5000
  #   networks:
  #     - fertiwell-network
  #   depends_on:
  #     - backend
  #   restart: unless-stopped

  # Backend Production Service
  backend:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: fertiwell-backend-prod
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
    volumes:
      - ./serviceAccountKey.json:/app/serviceAccountKey.json:ro
    networks:
      - fertiwell-network
    restart: unless-stopped

networks:
  fertiwell-network:
    driver: bridge
